workflows:
  ios-workflow:
    name: iOS Build

    environment:
      node: 22
      xcode: latest

    scripts:
      - node -v
      - npm install
      - npm install @capacitor/core @capacitor/cli

      - npx cap sync ios

    artifacts:
      - ios/App/build/**/*.app
