workflows:
  ios-workflow:
    name: iOS Build

    environment:
      node: 18
      xcode: latest

    scripts:
      - npm cache clean --force
      - rm -rf node_modules package-lock.json
      - npm install

      - npm install @capacitor/core @capacitor/cli

      # 🔥 fix permission issue
      - chmod +x node_modules/.bin/* || true

      - npx cap sync ios

    artifacts:
      - ios/App/build/**/*.app
